### ISSUE TITLE
업무 분담

### ISSUE THREAD

**Issue by cotgyu** [5oldman/EduProject#1]
1.	게시판 ,각 강좌 내 질문답변 게시판, 한줄평, 추천/비추천 
2.	코스별 강좌 소개 및 재생, 강좌 리스트 나열, 유튜브 플레이어 재생 ++ 
3.	회원 가입, 로그인, id/pw찾기 , 소셜로그인, 이메일 인증 회원가입
4.	영상 추천 알고리즘 , 채팅  , 수강 언어 에 따른 직업추천 , 연봉정보등
5.	wanted

**Comment by 5oldman** [comment]
#1 
게시판, 질문답변 게시판, 한줄평, 추천/비추천 - 민상훈
#2 
코스별 강좌 소개 및 재생, 강좌 리스트 나열, 유튜브 플레이어
